version: 2

project_name: hook-chain

release:
  draft: false
  prerelease: auto
  make_latest: true
  name_template: "v{{ .Version }}"
  header: |
    ## hook-chain {{ .Version }}

    **Sequential Hook Executor** — chain multiple hooks for Claude Code.
  footer: |
    ## Installation

    **Homebrew:**
    ```bash
    brew tap Fuabioo/tap
    brew install hook-chain
    ```

    **Go:**
    ```bash
    go install github.com/Fuabioo/hook-chain@latest
    ```

    ---
    **Full Changelog**: https://github.com/Fuabioo/hook-chain/compare/{{ .PreviousTag }}...{{ .Tag }}

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: hook-chain
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/Fuabioo/hook-chain/internal/cli.Version={{.Version}}
      - -X github.com/Fuabioo/hook-chain/internal/cli.Commit={{.ShortCommit}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ if .Logins }} ({{ .Logins | englishJoin }}){{ end }}"
  sort: asc
  filters:
    exclude:
      - "skip ci"
      - "skip-ci"
      - "^test:"
      - "^test\\("
  groups:
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?(fix|correct|patch)(\(.+\))??!?:.+$'
      order: 1
    - title: "Documentation"
      regexp: '^.*?docs?(\(.+\))??!?:.+$'
      order: 2
    - title: "Improvements"
      regexp: '^.*?(improve|enhance|optimize|refactor|perf)(\(.+\))??!?:.+$'
      order: 3
    - title: "Cleanup"
      regexp: '^.*?(cleanup|chore|ci|build)(\(.+\))??!?:.+$'
      order: 4
    - title: "Others"
      order: 999

homebrew_casks:
  - repository:
      owner: Fuabioo
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/Fuabioo/hook-chain"
    description: "Sequential Hook Executor — chain multiple hooks for Claude Code"
    license: "MIT"
